#ifndef BEVDEFS_H
#define BEVDEFS_H

#define BEV_SLIDER_BG 0
#define BEV_SLIDER_HANDLE 16
#define BEV_SLIDER_HANDLE_ACTIVE 32
#define BEV_CURSOR 48
#define BEV_SELECTED_SEQUENCE_ROW 64
#define BEV_SEQUENCE_BORDER 80
#define BEV_SEQUENCE_LOOP 96
#define BEV_THIN_FRAME 112
#define BEV_SELECTED_PATTERN_ROW 128
#define BEV_FIELD 144
#define BEV_SEPARATOR 160
#define BEV_SEQUENCE_PLAY_POS 176
#define BEV_BACKGROUND 192
#define BEV_MENUBAR 208
#define BEV_MENU 224
#define BEV_MENU_SELECTED 240
#define BEV_SELECTION 256
#define BEV_BUTTON 272
#define BEV_BUTTON_ACTIVE 288
#define DECAL_UPARROW 0 
#define DECAL_DOWNARROW 16
#define DECAL_GRAB_VERT 32
#define DECAL_GRAB_HORIZ 48
#define DECAL_TICK 64
#define DECAL_PLUS 80
#define DECAL_MINUS 96
#define DECAL_AUDIO_ENABLED 112
#define DECAL_AUDIO_DISABLED 128
#define DECAL_RIGHTARROW 144
#define DECAL_LEFTARROW 160
#define DECAL_CLOSE 176

#endif
